# Generated by Django 5.0.4 on 2024-04-27 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easychoiceapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pdetails',
        ),
        migrations.AlterField(
            model_name='product',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Pens'), (2, 'Calculators'), (3, 'Art & Colors'), (4, 'Diaries & Notebooks')], verbose_name='Category'),
        ),
    ]
